[I 200703 08:28:45 inrepo:35] Testing notebook docs/examples/vtb1_1.ipynb
[E 200703 08:28:45 __init__:79] Notebook JSON is invalid: {'model_id': '8af43b1e8b8949568ad3816806e7d09b'} is not valid under any of the given schemas
    
    Failed validating 'oneOf' in display_data['properties']['data']['patternProperties']['^(?!application/json$)[a-zA-Z0-9]+/[a-zA-Z0-9\\-\\+\\.]+$']:
    
    On instance['cells'][12]['outputs'][0]['data']['application/vnd.jupyter.widget-view+json']:
    {'model_id': '8af43b1e8b8949568ad3816806e7d09b'}
[I 200703 08:28:46 execute:404] Executing notebook with kernel: python3
Traceback (most recent call last):
  File "/src/inrepo.py", line 76, in <module>
    main()
  File "/src/inrepo.py", line 72, in main
    test_f(opts.test, opts.output_dir)
  File "/src/inrepo.py", line 38, in run_notebook
    exported = executenb(nb, cwd=os.path.dirname(nb_path))
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 737, in executenb
    return ep.preprocess(nb, resources, km=km)[0]
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 405, in preprocess
    nb, resources = super(ExecutePreprocessor, self).preprocess(nb, resources)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 69, in preprocess
    nb.cells[index], resources = self.preprocess_cell(cell, resources, index)
  File "/srv/conda/envs/notebook/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 448, in preprocess_cell
    raise CellExecutionError.from_cell_and_msg(cell, out)
nbconvert.preprocessors.execute.CellExecutionError: An error occurred while executing the following cell:
------------------
vtb.time_plot(m=10, c=1, k=100, x0=1, v0=-1, max_time=10)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mAttributeError[0m                            Traceback (most recent call last)
[0;32m<ipython-input-6-73066c5741dd>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mvtb[0m[0;34m.[0m[0mtime_plot[0m[0;34m([0m[0mm[0m[0;34m=[0m[0;36m10[0m[0;34m,[0m [0mc[0m[0;34m=[0m[0;36m1[0m[0;34m,[0m [0mk[0m[0;34m=[0m[0;36m100[0m[0;34m,[0m [0mx0[0m[0;34m=[0m[0;36m1[0m[0;34m,[0m [0mv0[0m[0;34m=[0m[0;34m-[0m[0;36m1[0m[0;34m,[0m [0mmax_time[0m[0;34m=[0m[0;36m10[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mAttributeError[0m: module 'vibration_toolbox' has no attribute 'time_plot'
AttributeError: module 'vibration_toolbox' has no attribute 'time_plot'


Container exited with status: {'Error': None, 'StatusCode': 1}
